from __future__ import annotations

PDF_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "Short title":"Short title","Overview":"Overview","Classification":"Classification","Publication, Validity & Revision":"Publication, Validity & Revision","Technical & Organization":"Technical & Organization","Description":"Description","Scope":"Scope","Requirements":"Requirements","Keywords":"Keywords","SDG Goals":"SDG Goals","References & Relationships":"References & Relationships","Hindi / Internationalization":"Hindi / Internationalization","Source Information":"Source Information","Related Standards":"Related Standards","Status":"Status","Department":"Department","Department Alias":"Department Alias","Aspect":"Aspect","Domain":"Domain","Year":"Year","Language":"Language","Group Classification":"Group Classification","Group":"Group","Sub Group":"Sub Group","Sub Sub Group":"Sub Sub Group","Published On":"Published On","Valid Upto":"Valid Upto","Review On":"Review On","Reaffirmation Year":"Reaffirmation Year","No. of Revision":"No. of Revision","Amendment Count":"Amendment Count","Latest Version":"Latest Version","Standard Base":"Standard Base","ICS Code":"ICS Code","Degree of Equivalence":"Degree of Equivalence","Ministry":"Ministry","Committee":"Committee","Member Secretary":"Member Secretary","Certification":"Certification","QCO Gazette":"QCO Gazette","Cross References":"Cross References","Referenced By":"Referenced By","Supersedes":"Supersedes","Superseded By":"Superseded By","Hindi Title":"Hindi Title","Hindi Scope":"Hindi Scope","Hindi Requirements":"Hindi Requirements","Source Standard ID":"Source Standard ID","Source Standard Enc ID":"Source Standard Enc ID","Source Department ID":"Source Department ID","Source Committee ID":"Source Committee ID","Raw IS Status":"Raw IS Status","IS Number":"IS Number","Title":"Title","Relationship":"Relationship","Mandatory Certification":"Mandatory Certification",
    },
    "hi": {
        "Short title":"संक्षिप्त शीर्षक","Overview":"अवलोकन","Classification":"वर्गीकरण","Publication, Validity & Revision":"प्रकाशन, वैधता एवं संशोधन","Technical & Organization":"तकनीकी एवं संगठन","Description":"विवरण","Scope":"दायरा","Requirements":"आवश्यकताएँ","Keywords":"कीवर्ड","SDG Goals":"एसडीजी लक्ष्य","References & Relationships":"संदर्भ एवं संबंध","Hindi / Internationalization":"हिंदी / अंतर्राष्ट्रीयकरण","Source Information":"स्रोत जानकारी","Related Standards":"संबंधित मानक","Status":"स्थिति","Department":"विभाग","Department Alias":"विभाग उपनाम","Aspect":"पहलू","Domain":"क्षेत्र","Year":"वर्ष","Language":"भाषा","Group Classification":"समूह वर्गीकरण","Group":"समूह","Sub Group":"उप-समूह","Sub Sub Group":"उप-उप-समूह","Published On":"प्रकाशित दिनांक","Valid Upto":"वैधता दिनांक","Review On":"समीक्षा दिनांक","Reaffirmation Year":"पुनर्पुष्टि वर्ष","No. of Revision":"संशोधनों की संख्या","Amendment Count":"संशोधन संख्या","Latest Version":"नवीनतम संस्करण","Standard Base":"मानक आधार","ICS Code":"आईसीएस कोड","Degree of Equivalence":"समतुल्यता की डिग्री","Ministry":"मंत्रालय","Committee":"समिति","Member Secretary":"सदस्य सचिव","Certification":"प्रमाणीकरण","QCO Gazette":"क्यूसीओ राजपत्र","Cross References":"क्रॉस संदर्भ","Referenced By":"द्वारा संदर्भित","Supersedes":"का स्थान लेता है","Superseded By":"द्वारा प्रतिस्थापित","Hindi Title":"हिंदी शीर्षक","Hindi Scope":"हिंदी दायरा","Hindi Requirements":"हिंदी आवश्यकताएँ","Source Standard ID":"स्रोत मानक आईडी","Source Standard Enc ID":"स्रोत मानक एन्क आईडी","Source Department ID":"स्रोत विभाग आईडी","Source Committee ID":"स्रोत समिति आईडी","Raw IS Status":"कच्ची आईएस स्थिति","IS Number":"आईएस संख्या","Title":"शीर्षक","Relationship":"संबंध","Mandatory Certification":"अनिवार्य प्रमाणीकरण",
    },
}
