from __future__ import annotations

# Generated by scripts/translate_standards.py. Keep this file deterministic by committing the generated output.
EXTRA_TRANSLATIONS: dict[str, dict[str, dict[str, object]]] = {}
