"""Mock BIS standards used to demo the recommender end-to-end.

Realistic IS numbers and requirements across four focus domains. `related`
lists sibling IS numbers resolved into standard_relationships at seed time.
"""

STANDARDS = [
    # --- Cement / Civil Engineering ---
    {
        "is_number": "IS 269:2015",
        "title": "Ordinary Portland Cement, 33 Grade — Specification",
        "status": "Active",
        "department": "Civil Engineering",
        "aspect": "Specification",
        "domain": "cement",
        "year": 2015,
        "reaffirmation_year": 2020,
        "scope": "Physical and chemical requirements for 33 grade ordinary Portland cement.",
        "keywords": ["cement", "portland", "opc", "33 grade", "concrete", "fineness", "setting time", "compressive strength"],
        "requirements": [
            "28-day compressive strength not less than 33 MPa",
            "Initial setting time not less than 30 minutes",
            "Fineness by specific surface not less than 225 m2/kg",
            "Soundness by Le-Chatelier expansion not more than 10 mm",
        ],
        "related": ["IS 4031-4:1988", "IS 8112:2013"],
    },
    {
        "is_number": "IS 8112:2013",
        "title": "Ordinary Portland Cement, 43 Grade — Specification",
        "status": "Active",
        "department": "Civil Engineering",
        "aspect": "Specification",
        "domain": "cement",
        "year": 2013,
        "reaffirmation_year": 2018,
        "scope": "Requirements for 43 grade OPC widely used in RCC and general construction.",
        "keywords": ["cement", "portland", "opc", "43 grade", "rcc", "concrete", "compressive strength", "construction"],
        "requirements": [
            "28-day compressive strength not less than 43 MPa",
            "Initial setting time not less than 30 minutes",
            "Final setting time not more than 600 minutes",
            "Fineness not less than 225 m2/kg",
        ],
        "related": ["IS 269:2015", "IS 12269:2013", "IS 456:2000"],
    },
    {
        "is_number": "IS 12269:2013",
        "title": "Ordinary Portland Cement, 53 Grade — Specification",
        "status": "Active",
        "department": "Civil Engineering",
        "aspect": "Specification",
        "domain": "cement",
        "year": 2013,
        "reaffirmation_year": 2019,
        "scope": "High-strength 53 grade OPC for structural and precast concrete.",
        "keywords": ["cement", "portland", "opc", "53 grade", "high strength", "precast", "structural concrete"],
        "requirements": [
            "28-day compressive strength not less than 53 MPa",
            "Initial setting time not less than 30 minutes",
            "Fineness not less than 225 m2/kg",
        ],
        "related": ["IS 8112:2013", "IS 456:2000"],
    },
    {
        "is_number": "IS 1489-1:2015",
        "title": "Portland Pozzolana Cement (Fly Ash Based) — Specification",
        "status": "Active",
        "department": "Civil Engineering",
        "aspect": "Specification",
        "domain": "cement",
        "year": 2015,
        "reaffirmation_year": None,
        "scope": "Blended cement with fly ash for durability and lower heat of hydration.",
        "keywords": ["cement", "ppc", "pozzolana", "fly ash", "blended", "durability", "hydration"],
        "requirements": [
            "Fly ash content between 15 and 35 percent by mass",
            "28-day compressive strength not less than 33 MPa",
            "Drying shrinkage not more than 0.15 percent",
        ],
        "related": ["IS 269:2015"],
    },
    {
        "is_number": "IS 4031-4:1988",
        "title": "Methods of Physical Tests for Hydraulic Cement — Part 4 Fineness",
        "status": "Active",
        "department": "Civil Engineering",
        "aspect": "Methods of Test",
        "domain": "cement",
        "year": 1988,
        "reaffirmation_year": 2019,
        "scope": "Test method for determining fineness of cement by Blaine air permeability.",
        "keywords": ["cement", "test method", "fineness", "blaine", "specific surface", "air permeability"],
        "requirements": [
            "Fineness determined by Blaine air permeability apparatus",
            "Report specific surface area in m2/kg",
        ],
        "related": ["IS 269:2015"],
    },
    {
        "is_number": "IS 456:2000",
        "title": "Plain and Reinforced Concrete — Code of Practice",
        "status": "Active",
        "department": "Civil Engineering",
        "aspect": "Code of Practice",
        "domain": "cement",
        "year": 2000,
        "reaffirmation_year": 2021,
        "scope": "Design, materials, workmanship and durability for concrete structures.",
        "keywords": ["concrete", "reinforced", "rcc", "design", "durability", "mix", "cover", "code of practice"],
        "requirements": [
            "Minimum grade of concrete for RCC is M20",
            "Nominal cover to reinforcement based on exposure condition",
            "Maximum water-cement ratio limited by exposure class",
        ],
        "related": ["IS 8112:2013", "IS 12269:2013"],
    },
    {
        "is_number": "IS 269:1989",
        "title": "Ordinary Portland Cement, 33 Grade — Specification (Third Revision)",
        "status": "Superseded",
        "department": "Civil Engineering",
        "aspect": "Specification",
        "domain": "cement",
        "year": 1989,
        "reaffirmation_year": None,
        "scope": "Earlier revision of 33 grade OPC, superseded by IS 269:2015.",
        "keywords": ["cement", "portland", "opc", "33 grade", "superseded"],
        "requirements": ["Superseded by IS 269:2015"],
        "related": ["IS 269:2015"],
    },

    # --- Textiles ---
    {
        "is_number": "IS 1969-1:2018",
        "title": "Textiles — Determination of Breaking Force and Elongation of Fabrics",
        "status": "Active",
        "department": "Textiles",
        "aspect": "Methods of Test",
        "domain": "textiles",
        "year": 2018,
        "reaffirmation_year": None,
        "scope": "Strip method for tensile strength and elongation of woven fabrics.",
        "keywords": ["textile", "fabric", "tensile", "breaking force", "elongation", "woven", "strip method"],
        "requirements": [
            "Test specimens conditioned at 27 C and 65 percent RH",
            "Report breaking force in newtons and elongation in percent",
        ],
        "related": ["IS 764:2021"],
    },
    {
        "is_number": "IS 764:2021",
        "title": "Cotton Sewing Threads — Specification",
        "status": "Active",
        "department": "Textiles",
        "aspect": "Specification",
        "domain": "textiles",
        "year": 2021,
        "reaffirmation_year": None,
        "scope": "Count, ply, strength and finish requirements for cotton sewing threads.",
        "keywords": ["textile", "cotton", "sewing thread", "count", "ply", "tensile strength", "finish"],
        "requirements": [
            "Single thread breaking strength as per nominal count",
            "Twist direction and twist per metre within stated tolerance",
        ],
        "related": ["IS 1969-1:2018"],
    },
    {
        "is_number": "IS 15801:2017",
        "title": "Textiles — Determination of Colour Fastness to Washing",
        "status": "Active",
        "department": "Textiles",
        "aspect": "Methods of Test",
        "domain": "textiles",
        "year": 2017,
        "reaffirmation_year": None,
        "scope": "Assess colour change and staining of textiles after washing.",
        "keywords": ["textile", "colour fastness", "washing", "staining", "grey scale", "dye"],
        "requirements": [
            "Colour change rated on grey scale, minimum grade 3-4",
            "Staining on adjacent fabric rated on grey scale",
        ],
        "related": ["IS 17263:2019"],
    },
    {
        "is_number": "IS 17263:2019",
        "title": "Textiles — Care Labelling Code Using Symbols",
        "status": "Active",
        "department": "Textiles",
        "aspect": "Code of Practice",
        "domain": "textiles",
        "year": 2019,
        "reaffirmation_year": None,
        "scope": "Standard symbols for washing, bleaching, drying and ironing care.",
        "keywords": ["textile", "care label", "symbols", "washing", "ironing", "drying", "labelling"],
        "requirements": [
            "Care symbols shown in fixed sequence: wash, bleach, dry, iron, professional care",
        ],
        "related": ["IS 15801:2017"],
    },
    {
        "is_number": "IS 11871:2019",
        "title": "Cotton Bed Sheets and Bed Sheeting — Specification",
        "status": "Draft",
        "department": "Textiles",
        "aspect": "Specification",
        "domain": "textiles",
        "year": 2019,
        "reaffirmation_year": None,
        "scope": "Dimensions, thread count and colour fastness for cotton bed sheets.",
        "keywords": ["textile", "bed sheet", "cotton", "thread count", "dimensions", "colour fastness"],
        "requirements": [
            "Thread count declared per 10 cm in warp and weft",
            "Colour fastness to washing minimum grade 3",
        ],
        "related": ["IS 15801:2017"],
    },

    # --- Electronics ---
    {
        "is_number": "IS 616:2017",
        "certification": "Mandatory BIS Certification under QCO",
        "has_qco_gazette": "Yes",
        "title": "Audio, Video and Similar Electronic Apparatus — Safety Requirements",
        "status": "Active",
        "department": "Electronics & IT",
        "aspect": "Specification",
        "domain": "electronics",
        "year": 2017,
        "reaffirmation_year": None,
        "scope": "Electrical safety for mains-powered audio/video equipment.",
        "keywords": ["electronics", "audio", "video", "safety", "mains", "insulation", "leakage current"],
        "requirements": [
            "Protection against electric shock under normal and fault conditions",
            "Insulation resistance and dielectric strength within limits",
        ],
        "related": ["IS 13252-1:2010"],
    },
    {
        "is_number": "IS 13252-1:2010",
        "title": "Information Technology Equipment — Safety, General Requirements",
        "status": "Active",
        "department": "Electronics & IT",
        "aspect": "Specification",
        "domain": "electronics",
        "year": 2010,
        "reaffirmation_year": 2018,
        "scope": "Safety of IT equipment including power supplies and enclosures.",
        "keywords": ["electronics", "it equipment", "safety", "power supply", "enclosure", "shock", "fire"],
        "requirements": [
            "Accessible parts within touch-current limits",
            "Fire enclosure materials meet flammability class",
        ],
        "related": ["IS 616:2017", "IS 16046-1:2018"],
    },
    {
        "is_number": "IS 16046-1:2018",
        "title": "Secondary Lithium Cells and Batteries — Safety Requirements",
        "status": "Active",
        "department": "Electronics & IT",
        "aspect": "Specification",
        "domain": "electronics",
        "year": 2018,
        "reaffirmation_year": None,
        "scope": "Safety of portable sealed lithium-ion cells and batteries.",
        "keywords": ["electronics", "lithium", "battery", "cell", "safety", "overcharge", "short circuit", "li-ion"],
        "requirements": [
            "Withstand overcharge, over-discharge and external short circuit",
            "No fire or explosion under crush and thermal abuse tests",
        ],
        "related": ["IS 13252-1:2010"],
    },
    {
        "is_number": "IS 1293:2019",
        "certification": "BIS Certification (ISI Mark)",
        "has_qco_gazette": "No",
        "title": "Plugs and Socket-Outlets of Rated Voltage up to 250 V — Specification",
        "status": "Active",
        "department": "Electronics & IT",
        "aspect": "Specification",
        "domain": "electronics",
        "year": 2019,
        "reaffirmation_year": None,
        "scope": "Dimensions and safety for domestic plugs and socket-outlets.",
        "keywords": ["electronics", "plug", "socket", "connector", "250v", "shutter", "earthing"],
        "requirements": [
            "Socket-outlets provided with protective shutters",
            "Temperature rise on terminals within limits under rated current",
        ],
        "related": ["IS 616:2017"],
    },
    {
        "is_number": "IS 302-1:2008",
        "certification": "Mandatory BIS Certification under QCO",
        "has_qco_gazette": "Yes",
        "title": "Household and Similar Electrical Appliances — Safety, General Requirements",
        "status": "Withdrawn",
        "department": "Electronics & IT",
        "aspect": "Specification",
        "domain": "electronics",
        "year": 2008,
        "reaffirmation_year": None,
        "scope": "General safety for household appliances; withdrawn pending revision.",
        "keywords": ["electronics", "appliance", "household", "safety", "withdrawn"],
        "requirements": ["Under revision; refer latest amendment"],
        "related": ["IS 13252-1:2010"],
    },

    # --- Food Safety ---
    {
        "is_number": "IS 10500:2012",
        "certification": "BIS Certification (ISI Mark) recommended for packaged water units",
        "has_qco_gazette": "No",
        "title": "Drinking Water — Specification",
        "status": "Active",
        "department": "Food & Agriculture",
        "aspect": "Specification",
        "domain": "food_safety",
        "year": 2012,
        "reaffirmation_year": 2021,
        "scope": "Acceptable and permissible limits for potable drinking water.",
        "keywords": ["food", "drinking water", "potable", "ph", "turbidity", "tds", "arsenic", "fluoride", "microbial"],
        "requirements": [
            "pH between 6.5 and 8.5",
            "Turbidity acceptable limit 1 NTU",
            "Total dissolved solids acceptable limit 500 mg/l",
            "Arsenic not more than 0.01 mg/l",
        ],
        "related": ["IS 14543:2016", "IS 5402:2012"],
    },
    {
        "is_number": "IS 14543:2016",
        "certification": "Mandatory BIS Certification under QCO",
        "has_qco_gazette": "Yes",
        "title": "Packaged Drinking Water (Other Than Mineral Water) — Specification",
        "status": "Active",
        "department": "Food & Agriculture",
        "aspect": "Specification",
        "domain": "food_safety",
        "year": 2016,
        "reaffirmation_year": None,
        "scope": "Requirements for packaged drinking water and its processing.",
        "keywords": ["food", "packaged water", "bottled water", "drinking water", "processing", "microbial", "ph"],
        "requirements": [
            "Absence of E. coli in 250 ml",
            "pH between 6.5 and 8.5",
            "Residual free chlorine limits after ozonation",
        ],
        "related": ["IS 10500:2012"],
    },
    {
        "is_number": "IS 1165:2002",
        "title": "Milk Powder — Specification",
        "status": "Active",
        "department": "Food & Agriculture",
        "aspect": "Specification",
        "domain": "food_safety",
        "year": 2002,
        "reaffirmation_year": 2019,
        "scope": "Composition and hygiene requirements for whole and skimmed milk powder.",
        "keywords": ["food", "milk powder", "dairy", "moisture", "fat", "protein", "hygiene"],
        "requirements": [
            "Moisture not more than 4 percent for whole milk powder",
            "Milk fat not less than 26 percent for whole milk powder",
            "Free from added preservatives and colouring matter",
        ],
        "related": ["IS 5402:2012"],
    },
    {
        "is_number": "IS 5402:2012",
        "title": "Microbiology of Food — Horizontal Method for Enumeration of Microorganisms",
        "status": "Active",
        "department": "Food & Agriculture",
        "aspect": "Methods of Test",
        "domain": "food_safety",
        "year": 2012,
        "reaffirmation_year": None,
        "scope": "Colony-count technique at 30 C for microorganisms in food.",
        "keywords": ["food", "microbiology", "colony count", "enumeration", "microorganism", "plate count"],
        "requirements": [
            "Incubate plates at 30 C for 72 hours",
            "Report colony forming units per gram or millilitre",
        ],
        "related": ["IS 10500:2012", "IS 1165:2002"],
    },
]
