"""A few extra standards in more engineering domains so the coverage chart
mirrors a fuller BIS catalogue. English only; localization falls back to English.
"""

EXTRA = [
    {
        "is_number": "IS 2062:2011",
        "title": "Hot Rolled Medium and High Tensile Structural Steel — Specification",
        "status": "Active",
        "department": "Mechanical Engineering",
        "aspect": "Specification",
        "domain": "mechanical",
        "year": 2011,
        "reaffirmation_year": 2018,
        "scope": "Structural steel for general and structural engineering applications.",
        "keywords": ["steel", "structural", "tensile", "mechanical", "hot rolled", "yield strength"],
        "requirements": ["Yield stress per grade designation", "Elongation percentage as specified"],
        "related": [],
    },
    {
        "is_number": "IS 1239-1:2004",
        "title": "Steel Tubes, Tubulars and Other Wrought Steel Fittings — Specification",
        "status": "Active",
        "department": "Mechanical Engineering",
        "aspect": "Specification",
        "domain": "mechanical",
        "year": 2004,
        "reaffirmation_year": 2015,
        "scope": "Welded and seamless steel tubes for water, gas and general purposes.",
        "keywords": ["steel", "tube", "pipe", "mechanical", "fitting", "welded"],
        "requirements": ["Hydraulic test pressure withstood", "Mass per metre within tolerance"],
        "related": [],
    },
    {
        "is_number": "IS 265:2021",
        "title": "Hydrochloric Acid — Specification",
        "status": "Active",
        "department": "Chemical Engineering",
        "aspect": "Specification",
        "domain": "chemical",
        "year": 2021,
        "reaffirmation_year": None,
        "scope": "Requirements for commercial and pure grades of hydrochloric acid.",
        "keywords": ["acid", "hydrochloric", "chemical", "purity", "reagent"],
        "requirements": ["Acidity as HCl within grade limits", "Iron content maximum per grade"],
        "related": [],
    },
    {
        "is_number": "IS 264:2005",
        "title": "Nitric Acid — Specification",
        "status": "Active",
        "department": "Chemical Engineering",
        "aspect": "Specification",
        "domain": "chemical",
        "year": 2005,
        "reaffirmation_year": 2016,
        "scope": "Requirements for technical and pure grades of nitric acid.",
        "keywords": ["acid", "nitric", "chemical", "purity", "reagent"],
        "requirements": ["Strength as HNO3 within grade limits", "Residue on ignition maximum"],
        "related": [],
    },
    {
        "is_number": "IS 2500-1:2000",
        "title": "Sampling Inspection Procedures — Attributes Sampling Plans",
        "status": "Active",
        "department": "Quality & Systems",
        "aspect": "Methods of Test",
        "domain": "others",
        "year": 2000,
        "reaffirmation_year": 2019,
        "scope": "Acceptance sampling plans indexed by acceptance quality limit.",
        "keywords": ["sampling", "inspection", "quality", "acceptance", "aql"],
        "requirements": ["Sample size per lot size and inspection level", "Acceptance number per AQL"],
        "related": [],
    },
    {
        "is_number": "IS 4905:2015",
        "title": "Random Sampling and Randomization Procedures",
        "status": "Active",
        "department": "Quality & Systems",
        "aspect": "Methods of Test",
        "domain": "others",
        "year": 2015,
        "reaffirmation_year": None,
        "scope": "Methods for random selection and randomization in inspection.",
        "keywords": ["random", "sampling", "quality", "randomization", "statistics"],
        "requirements": ["Use random number tables or generators", "Document selection method"],
        "related": [],
    },
]
