"""initial schema

Revision ID: 9b190b9aad17
Revises: 
Create Date: 2026-09-03 13:14:50.106140
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9b190b9aad17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('document_name', sa.String(length=512), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_created_at'), 'search_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_history_request_id'), 'search_history', ['request_id'], unique=False)
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('aspect', sa.String(length=128), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('reaffirmation_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_aspect'), 'standards', ['aspect'], unique=False)
    op.create_index(op.f('ix_standards_department'), 'standards', ['department'], unique=False)
    op.create_index(op.f('ix_standards_domain'), 'standards', ['domain'], unique=False)
    op.create_index(op.f('ix_standards_is_number'), 'standards', ['is_number'], unique=True)
    op.create_index(op.f('ix_standards_status'), 'standards', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('matched_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_request_id'), 'recommendations', ['request_id'], unique=False)
    op.create_index(op.f('ix_recommendations_standard_id'), 'recommendations', ['standard_id'], unique=False)
    op.create_table('standard_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_standard_id', sa.Integer(), nullable=False),
    sa.Column('target_standard_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_relationships_source_standard_id'), 'standard_relationships', ['source_standard_id'], unique=False)
    op.create_index(op.f('ix_standard_relationships_target_standard_id'), 'standard_relationships', ['target_standard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standard_relationships_target_standard_id'), table_name='standard_relationships')
    op.drop_index(op.f('ix_standard_relationships_source_standard_id'), table_name='standard_relationships')
    op.drop_table('standard_relationships')
    op.drop_index(op.f('ix_recommendations_standard_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_request_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_standards_status'), table_name='standards')
    op.drop_index(op.f('ix_standards_is_number'), table_name='standards')
    op.drop_index(op.f('ix_standards_domain'), table_name='standards')
    op.drop_index(op.f('ix_standards_department'), table_name='standards')
    op.drop_index(op.f('ix_standards_aspect'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_search_history_request_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_created_at'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_table('documents')
    # ### end Alembic commands ###
