"""
One-off generator: turns the Gemini translation dicts into a frontend TypeScript file.

Usage (from the folder holding both .py files):
    python generate_gm_labels.py

Output: groupMinistryLabels.ts  -> copy to frontend/src/i18n/
"""
import unicodedata
from pathlib import Path

from ministry_translation import ministries_translations
from lenovo_group_translation import bis_group_translations

LANG_CODES = {
    "Hindi": "hi", "Bengali": "bn", "Telugu": "te", "Marathi": "mr",
    "Tamil": "ta", "Urdu": "ur", "Gujarati": "gu", "Kannada": "kn",
    "Malayalam": "ml", "Odia": "or", "Punjabi": "pa",
}

# Unicode script each language must be written in (used to catch copy/paste slips)
EXPECTED_SCRIPT = {
    "hi": "DEVANAGARI", "mr": "DEVANAGARI", "bn": "BENGALI", "te": "TELUGU",
    "ta": "TAMIL", "ur": "ARABIC", "gu": "GUJARATI", "kn": "KANNADA",
    "ml": "MALAYALAM", "or": "ORIYA", "pa": "GURMUKHI",
}

# Names present in the backend but missing from the Gemini file
MISSING = {"Ministry of Communications"}

skipped: list[str] = []


def scripts_of(text: str) -> set[str]:
    return {unicodedata.name(ch).split()[0] for ch in text if ch.isalpha()}


def ts_quote(text: str) -> str:
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def build(name: str, source: dict) -> str:
    lines = [f"export const {name}: LabelMap = {{"]
    for english, translations in source.items():
        parts = []
        for language, code in LANG_CODES.items():
            value = (translations.get(language) or "").strip()
            if not value:
                continue
            bad = scripts_of(value) - {EXPECTED_SCRIPT[code]}
            # "IT" style Latin acronyms are fine, other foreign scripts are not
            if bad - {"LATIN"}:
                skipped.append(f"{name} | {english} | {code} | {value}")
                continue
            parts.append(f"{code}: {ts_quote(value)}")
        lines.append(f"  {ts_quote(english)}: {{ {', '.join(parts)} }},")
    lines.append("}")
    return "\n".join(lines)


header = """import type { Lang } from './index'

// Generated by generate_gm_labels.py - keys are the exact English values the backend returns.
// English is intentionally omitted: labelFor() falls back to the key itself.
type LabelMap = Record<string, Partial<Record<Lang, string>>>

"""

body = build("GROUP_LABELS", bis_group_translations) + "\n\n" + build("MINISTRY_LABELS", ministries_translations) + "\n"
Path("groupMinistryLabels.ts").write_text(header + body, encoding="utf-8")

print(f"Groups: {len(bis_group_translations)}  Ministries: {len(ministries_translations)}")
print(f"Skipped {len(skipped)} wrong-script entries (they fall back to English):")
for row in skipped:
    print("  ", row)
for name in MISSING:
    if name not in ministries_translations:
        print(f"Missing from translation file: {name}")
