import type { Lang } from './index'

const PDF_COPY: Record<Lang, Record<string, string>> = {
  en: { label: 'BIS Intelligence', title: 'PDF Analysis', description: 'Upload a specification or technical PDF to extract its structure, identify BIS references, and find semantically relevant standards.', source: 'Source document', hint: 'Text is extracted page-by-page before semantic matching.', analysis: 'Document analysis', pages: 'Pages', readable: 'Readable pages', words: 'Words extracted', refs: 'BIS references', notes: 'Extraction notes', detected: '{pdfCopy(lang, "detected")}', none: '{pdfCopy(lang, "none")}', sections: '{pdfCopy(lang, "sections")}', noSections: '{pdfCopy(lang, "noSections")}', referenced: '{pdfCopy(lang, "referenced")}', noRefs: '{pdfCopy(lang, "noRefs")}', details: '{pdfCopy(lang, "details")}', ready: 'Ready for document analysis', readyDesc: 'The analysis will inspect the PDF text layer, page coverage, BIS numbers, standard sections, references, and semantic similarity.', recommended: 'Recommended standards', recommendedDesc: 'Matches generated from the extracted PDF content, detected references, and document structure.', matches: 'matches', failed: 'PDF analysis failed', matched: 'BIS standards matched', page: 'Page' },
  hi: { label: 'बीआईएस इंटेलिजेंस', title: 'पीडीएफ विश्लेषण', description: 'संरचना निकालने, BIS संदर्भ पहचानने और प्रासंगिक मानक खोजने के लिए विनिर्देश या तकनीकी PDF अपलोड करें।', source: 'स्रोत दस्तावेज़', hint: 'सिमेंटिक मिलान से पहले पाठ को पृष्ठ-दर-पृष्ठ निकाला जाता है।', analysis: 'दस्तावेज़ विश्लेषण', pages: 'पृष्ठ', readable: 'पठनीय पृष्ठ', words: 'निकाले गए शब्द', refs: 'BIS संदर्भ', notes: 'निष्कर्षण टिप्पणियाँ', detected: 'पहचाने गए BIS मानक', none: 'कोई नहीं मिला', sections: 'दस्तावेज़ अनुभाग', noSections: 'मानक अनुभाग शीर्षक नहीं मिले', referenced: 'संदर्भित मानक', noRefs: 'कोई IS संदर्भ नहीं मिला', details: 'पृष्ठ निष्कर्षण विवरण', ready: 'दस्तावेज़ विश्लेषण के लिए तैयार', readyDesc: 'विश्लेषण PDF टेक्स्ट लेयर, पृष्ठ कवरेज, BIS नंबर, मानक अनुभाग, संदर्भ और सिमेंटिक समानता की जाँच करेगा।', recommended: 'अनुशंसित मानक', recommendedDesc: 'निकाले गए PDF कंटेंट, पहचाने गए संदर्भों और दस्तावेज़ संरचना से मिलान तैयार किए गए हैं।', matches: 'मिलान', failed: 'PDF विश्लेषण विफल हुआ', matched: 'BIS मानक मिले', page: 'पृष्ठ' },
  ta: { label: 'BIS நுண்ணறிவு', title: 'PDF பகுப்பாய்வு', description: 'கட்டமைப்பை பிரித்தெடுக்கவும், BIS குறிப்புகளை அடையாளம் காணவும், பொருத்தமான தரநிலைகளைக் கண்டறியவும் PDF ஐ பதிவேற்றவும்.', source: 'மூல ஆவணம்', hint: 'சொற்பொருள் பொருத்தத்திற்கு முன் உரை ஒவ்வொரு பக்கமாக பிரித்தெடுக்கப்படுகிறது.', analysis: 'ஆவண பகுப்பாய்வு', pages: 'பக்கங்கள்', readable: 'படிக்கக்கூடிய பக்கங்கள்', words: 'பிரித்தெடுக்கப்பட்ட சொற்கள்', refs: 'BIS குறிப்புகள்', notes: 'பிரித்தெடுப்பு குறிப்புகள்', detected: 'கண்டறியப்பட்ட BIS தரநிலைகள்', none: 'எதுவும் கண்டறியப்படவில்லை', sections: 'ஆவணப் பிரிவுகள்', noSections: 'தரநிலைப் பிரிவு தலைப்புகள் எதுவும் கண்டறியப்படவில்லை', referenced: 'குறிப்பிடப்பட்ட தரநிலைகள்', noRefs: 'IS குறிப்புகள் எதுவும் கண்டறியப்படவில்லை', details: 'பக்கப் பிரித்தெடுப்பு விவரங்கள்', ready: 'ஆவணப் பகுப்பாய்வுக்குத் தயார்', readyDesc: 'PDF உரை அடுக்கு, பக்கக் கவரேஜ், BIS எண்கள், பிரிவுகள், குறிப்புகள் மற்றும் சொற்பொருள் ஒற்றுமையை பகுப்பாய்வு செய்யும்.', recommended: 'பரிந்துரைக்கப்பட்ட தரநிலைகள்', recommendedDesc: 'பிரித்தெடுக்கப்பட்ட PDF உள்ளடக்கம் மற்றும் கண்டறியப்பட்ட குறிப்புகளிலிருந்து பொருத்தங்கள் உருவாக்கப்பட்டன.', matches: 'பொருத்தங்கள்', failed: 'PDF பகுப்பாய்வு தோல்வியடைந்தது', matched: 'BIS தரநிலைகள் பொருந்தின', page: 'பக்கம்' },
  bn: { label: 'BIS ইন্টেলিজেন্স', title: 'PDF বিশ্লেষণ', description: 'কাঠামো বের করতে, BIS রেফারেন্স শনাক্ত করতে এবং প্রাসঙ্গিক মান খুঁজতে PDF আপলোড করুন।', source: 'উৎস নথি', hint: 'সেমান্টিক মিলের আগে প্রতি পৃষ্ঠা থেকে পাঠ্য বের করা হয়।', analysis: 'নথি বিশ্লেষণ', pages: 'পৃষ্ঠা', readable: 'পাঠযোগ্য পৃষ্ঠা', words: 'নিষ্কাশিত শব্দ', refs: 'BIS রেফারেন্স', notes: 'নিষ্কাশন নোট', detected: 'শনাক্ত BIS মান', none: 'কিছু পাওয়া যায়নি', sections: 'নথির বিভাগ', noSections: 'মানের বিভাগ শিরোনাম শনাক্ত হয়নি', referenced: 'উল্লেখিত মান', noRefs: 'কোনও IS রেফারেন্স শনাক্ত হয়নি', details: 'পৃষ্ঠা নিষ্কাশন বিবরণ', ready: 'নথি বিশ্লেষণের জন্য প্রস্তুত', readyDesc: 'PDF টেক্সট স্তর, পৃষ্ঠা কভারেজ, BIS নম্বর, বিভাগ, রেফারেন্স এবং সেমান্টিক সাদৃশ্য পরীক্ষা করবে।', recommended: 'প্রস্তাবিত মান', recommendedDesc: 'নিষ্কাশিত PDF বিষয়বস্তু ও শনাক্ত রেফারেন্স থেকে মিল তৈরি হয়েছে।', matches: 'মিল', failed: 'PDF বিশ্লেষণ ব্যর্থ হয়েছে', matched: 'BIS মান মিলে গেছে', page: 'পৃষ্ঠা' },
  te: { label: 'BIS ఇంటెలిజెన్స్', title: 'PDF విశ్లేషణ', description: 'నిర్మాణాన్ని వెలికితీయడానికి, BIS సూచనలను గుర్తించడానికి మరియు సంబంధిత ప్రమాణాలను కనుగొనడానికి PDF ను అప్‌లోడ్ చేయండి.', source: 'మూల పత్రం', hint: 'సెమాంటిక్ మ్యాచ్‌కు ముందు ప్రతి పేజీ నుంచి వచనం వెలికితీయబడుతుంది.', analysis: 'పత్ర విశ్లేషణ', pages: 'పేజీలు', readable: 'చదవగల పేజీలు', words: 'వెలికితీసిన పదాలు', refs: 'BIS సూచనలు', notes: 'వెలికితీత గమనికలు', detected: 'గుర్తించిన BIS ప్రమాణాలు', none: 'ఏవీ గుర్తించబడలేదు', sections: 'పత్ర విభాగాలు', noSections: 'ప్రమాణ విభాగ శీర్షికలు గుర్తించబడలేదు', referenced: 'సూచించిన ప్రమాణాలు', noRefs: 'IS సూచనలు ఏవీ గుర్తించబడలేదు', details: 'పేజీ వెలికితీత వివరాలు', ready: 'పత్ర విశ్లేషణకు సిద్ధం', readyDesc: 'PDF టెక్స్ట్ లేయర్, పేజీ కవరేజ్, BIS సంఖ్యలు, విభాగాలు, సూచనలు మరియు సెమాంటిక్ సారూప్యతను పరిశీలిస్తుంది.', recommended: 'సిఫార్సు చేసిన ప్రమాణాలు', recommendedDesc: 'వెలికితీసిన PDF కంటెంట్ మరియు గుర్తించిన సూచనల నుంచి మ్యాచ్‌లు రూపొందించబడ్డాయి.', matches: 'మ్యాచ్‌లు', failed: 'PDF విశ్లేషణ విఫలమైంది', matched: 'BIS ప్రమాణాలు సరిపోలాయి', page: 'పేజీ' },
  mr: { label: 'BIS इंटेलिजन्स', title: 'PDF विश्लेषण', description: 'रचना काढण्यासाठी, BIS संदर्भ ओळखण्यासाठी आणि संबंधित मानके शोधण्यासाठी PDF अपलोड करा.', source: 'स्रोत दस्तऐवज', hint: 'सिमेंटिक जुळणीपूर्वी मजकूर प्रत्येक पानातून काढला जातो.', analysis: 'दस्तऐवज विश्लेषण', pages: 'पाने', readable: 'वाचनीय पाने', words: 'काढलेले शब्द', refs: 'BIS संदर्भ', notes: 'निष्कर्षण नोंदी', detected: 'आढळलेली BIS मानके', none: 'काहीही आढळले नाही', sections: 'दस्तऐवज विभाग', noSections: 'मानक विभागांची शीर्षके आढळली नाहीत', referenced: 'संदर्भित मानके', noRefs: 'IS संदर्भ आढळले नाहीत', details: 'पान निष्कर्षण तपशील', ready: 'दस्तऐवज विश्लेषणासाठी तयार', readyDesc: 'PDF मजकूर स्तर, पानांचे कव्हरेज, BIS क्रमांक, विभाग, संदर्भ आणि सिमेंटिक साम्य तपासेल.', recommended: 'शिफारस केलेली मानके', recommendedDesc: 'काढलेल्या PDF मजकुरातून आणि आढळलेल्या संदर्भांमधून जुळण्या तयार केल्या आहेत.', matches: 'जुळण्या', failed: 'PDF विश्लेषण अयशस्वी झाले', matched: 'BIS मानके जुळली', page: 'पान' },
  gu: { label: 'BIS ઇન્ટેલિજન્સ', title: 'PDF વિશ્લેષણ', description: 'રચના કાઢવા, BIS સંદર્ભો ઓળખવા અને સંબંધિત ધોરણો શોધવા માટે PDF અપલોડ કરો.', source: 'સ્ત્રોત દસ્તાવેજ', hint: 'સેમેન્ટિક મેચિંગ પહેલાં દરેક પાનામાંથી ટેક્સ્ટ કાઢવામાં આવે છે.', analysis: 'દસ્તાવેજ વિશ્લેષણ', pages: 'પૃષ્ઠો', readable: 'વાંચી શકાય તેવા પૃષ્ઠો', words: 'કાઢેલા શબ્દો', refs: 'BIS સંદર્ભો', notes: 'નિષ્કર્ષણ નોંધો', detected: 'ઓળખાયેલા BIS ધોરણો', none: 'કંઈ મળ્યું નથી', sections: 'દસ્તાવેજ વિભાગો', noSections: 'ધોરણ વિભાગના શીર્ષકો મળ્યા નથી', referenced: 'સંદર્ભિત ધોરણો', noRefs: 'કોઈ IS સંદર્ભ મળ્યો નથી', details: 'પૃષ્ઠ નિષ્કર્ષણ વિગતો', ready: 'દસ્તાવેજ વિશ્લેષણ માટે તૈયાર', readyDesc: 'PDF ટેક્સ્ટ સ્તર, પૃષ્ઠ કવરેજ, BIS નંબરો, વિભાગો, સંદર્ભો અને સેમેન્ટિક સમાનતા તપાસશે.', recommended: 'ભલામણ કરેલ ધોરણો', recommendedDesc: 'કાઢેલા PDF વિષયવસ્તુ અને ઓળખાયેલા સંદર્ભોમાંથી મેચ તૈયાર કરવામાં આવ્યા છે.', matches: 'મેચ', failed: 'PDF વિશ્લેષણ નિષ્ફળ થયું', matched: 'BIS ધોરણો મળ્યા', page: 'પૃષ્ઠ' },
  kn: { label: 'BIS ಇಂಟೆಲಿಜೆನ್ಸ್', title: 'PDF ವಿಶ್ಲೇಷಣೆ', description: 'ರಚನೆಯನ್ನು ಹೊರತೆಗೆಯಲು, BIS ಉಲ್ಲೇಖಗಳನ್ನು ಗುರುತಿಸಲು ಮತ್ತು ಸಂಬಂಧಿತ ಮಾನದಂಡಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು PDF ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.', source: 'ಮೂಲ ದಾಖಲೆ', hint: 'ಸೆಮ್ಯಾಂಟಿಕ್ ಹೊಂದಾಣಿಕೆಯ ಮೊದಲು ಪ್ರತಿ ಪುಟದಿಂದ ಪಠ್ಯವನ್ನು ಹೊರತೆಗೆಯಲಾಗುತ್ತದೆ.', analysis: 'ದಾಖಲೆ ವಿಶ್ಲೇಷಣೆ', pages: 'ಪುಟಗಳು', readable: 'ಓದಬಹುದಾದ ಪುಟಗಳು', words: 'ಹೊರತೆಗೆಯಲಾದ ಪದಗಳು', refs: 'BIS ಉಲ್ಲೇಖಗಳು', notes: 'ಹೊರತೆಗೆಯುವ ಟಿಪ್ಪಣಿಗಳು', detected: 'ಪತ್ತೆಯಾದ BIS ಮಾನದಂಡಗಳು', none: 'ಯಾವುದೂ ಪತ್ತೆಯಾಗಿಲ್ಲ', sections: 'ದಾಖಲೆ ವಿಭಾಗಗಳು', noSections: 'ಮಾನದಂಡ ವಿಭಾಗದ ಶೀರ್ಷಿಕೆಗಳು ಪತ್ತೆಯಾಗಿಲ್ಲ', referenced: 'ಉಲ್ಲೇಖಿತ ಮಾನದಂಡಗಳು', noRefs: 'ಯಾವುದೇ IS ಉಲ್ಲೇಖಗಳು ಪತ್ತೆಯಾಗಿಲ್ಲ', details: 'ಪುಟ ಹೊರತೆಗೆಯುವ ವಿವರಗಳು', ready: 'ದಾಖಲೆ ವಿಶ್ಲೇಷಣೆಗೆ ಸಿದ್ಧ', readyDesc: 'PDF ಪಠ್ಯ ಪದರ, ಪುಟ ವ್ಯಾಪ್ತಿ, BIS ಸಂಖ್ಯೆಗಳು, ವಿಭಾಗಗಳು, ಉಲ್ಲೇಖಗಳು ಮತ್ತು ಸೆಮ್ಯಾಂಟಿಕ್ ಸಾಮ್ಯತೆಯನ್ನು ಪರಿಶೀಲಿಸುತ್ತದೆ.', recommended: 'ಶಿಫಾರಸು ಮಾಡಿದ ಮಾನದಂಡಗಳು', recommendedDesc: 'ಹೊರತೆಗೆಯಲಾದ PDF ವಿಷಯ ಮತ್ತು ಪತ್ತೆಯಾದ ಉಲ್ಲೇಖಗಳಿಂದ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ರಚಿಸಲಾಗಿದೆ.', matches: 'ಹೊಂದಾಣಿಕೆಗಳು', failed: 'PDF ವಿಶ್ಲೇಷಣೆ ವಿಫಲವಾಗಿದೆ', matched: 'BIS ಮಾನದಂಡಗಳು ಹೊಂದಿಕೆಯಾಗಿವೆ', page: 'ಪುಟ' },
  ml: { label: 'BIS ഇന്റലിജൻസ്', title: 'PDF വിശകലനം', description: 'ഘടന പുറത്തെടുക്കാനും BIS റഫറൻസുകൾ തിരിച്ചറിയാനും പ്രസക്തമായ മാനദണ്ഡങ്ങൾ കണ്ടെത്താനും PDF അപ്‌ലോഡ് ചെയ്യുക.', source: 'ഉറവിട രേഖ', hint: 'സെമാന്റിക് പൊരുത്തത്തിന് മുമ്പ് ഓരോ പേജിൽ നിന്നും ടെക്സ്റ്റ് പുറത്തെടുക്കുന്നു.', analysis: 'രേഖാ വിശകലനം', pages: 'പേജുകൾ', readable: 'വായിക്കാവുന്ന പേജുകൾ', words: 'പുറത്തെടുത്ത വാക്കുകൾ', refs: 'BIS റഫറൻസുകൾ', notes: 'എക്സ്ട്രാക്ഷൻ കുറിപ്പുകൾ', detected: 'കണ്ടെത്തിയ BIS മാനദണ്ഡങ്ങൾ', none: 'ഒന്നും കണ്ടെത്തിയില്ല', sections: 'രേഖാ വിഭാഗങ്ങൾ', noSections: 'മാനദണ്ഡ വിഭാഗ തലക്കെട്ടുകളൊന്നും കണ്ടെത്തിയില്ല', referenced: 'പരാമർശിച്ച മാനദണ്ഡങ്ങൾ', noRefs: 'IS റഫറൻസുകളൊന്നും കണ്ടെത്തിയില്ല', details: 'പേജ് എക്സ്ട്രാക്ഷൻ വിശദാംശങ്ങൾ', ready: 'രേഖാ വിശകലനത്തിന് തയ്യാറാണ്', readyDesc: 'PDF ടെക്സ്റ്റ് ലെയർ, പേജ് കവറേജ്, BIS നമ്പറുകൾ, വിഭാഗങ്ങൾ, റഫറൻസുകൾ, സെമാന്റിക് സാമ്യം എന്നിവ പരിശോധിക്കും.', recommended: 'ശുപാർശ ചെയ്ത മാനദണ്ഡങ്ങൾ', recommendedDesc: 'എക്സ്ട്രാക്റ്റ് ചെയ്ത PDF ഉള്ളടക്കത്തിൽ നിന്നും കണ്ടെത്തിയ റഫറൻസുകളിൽ നിന്നും പൊരുത്തങ്ങൾ സൃഷ്ടിച്ചു.', matches: 'പൊരുത്തങ്ങൾ', failed: 'PDF വിശകലനം പരാജയപ്പെട്ടു', matched: 'BIS മാനദണ്ഡങ്ങൾ പൊരുത്തപ്പെട്ടു', page: 'പേജ്' },
  pa: { label: 'BIS ਇੰਟੈਲੀਜੈਂਸ', title: 'PDF ਵਿਸ਼ਲੇਸ਼ਣ', description: 'ਢਾਂਚਾ ਕੱਢਣ, BIS ਹਵਾਲਿਆਂ ਦੀ ਪਛਾਣ ਕਰਨ ਅਤੇ ਸੰਬੰਧਿਤ ਮਿਆਰ ਲੱਭਣ ਲਈ PDF ਅਪਲੋਡ ਕਰੋ।', source: 'ਸਰੋਤ ਦਸਤਾਵੇਜ਼', hint: 'ਸੈਮੈਂਟਿਕ ਮਿਲਾਣ ਤੋਂ ਪਹਿਲਾਂ ਹਰ ਪੰਨੇ ਤੋਂ ਪਾਠ ਕੱਢਿਆ ਜਾਂਦਾ ਹੈ।', analysis: 'ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ', pages: 'ਪੰਨੇ', readable: 'ਪੜ੍ਹਨਯੋਗ ਪੰਨੇ', words: 'ਕੱਢੇ ਗਏ ਸ਼ਬਦ', refs: 'BIS ਹਵਾਲੇ', notes: 'ਨਿਕਾਸ ਨੋਟਸ', detected: 'ਪਛਾਣੇ ਗਏ BIS ਮਿਆਰ', none: 'ਕੁਝ ਨਹੀਂ ਮਿਲਿਆ', sections: 'ਦਸਤਾਵੇਜ਼ ਭਾਗ', noSections: 'ਮਿਆਰੀ ਭਾਗਾਂ ਦੇ ਸਿਰਲੇਖ ਨਹੀਂ ਮਿਲੇ', referenced: 'ਹਵਾਲਾ ਦਿੱਤੇ ਮਿਆਰ', noRefs: 'ਕੋਈ IS ਹਵਾਲਾ ਨਹੀਂ ਮਿਲਿਆ', details: 'ਪੰਨਾ ਨਿਕਾਸ ਵੇਰਵੇ', ready: 'ਦਸਤਾਵੇਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਤਿਆਰ', readyDesc: 'PDF ਟੈਕਸਟ ਲੇਅਰ, ਪੰਨਾ ਕਵਰੇਜ, BIS ਨੰਬਰ, ਭਾਗ, ਹਵਾਲੇ ਅਤੇ ਸੈਮੈਂਟਿਕ ਸਮਾਨਤਾ ਦੀ ਜਾਂਚ ਕਰੇਗਾ।', recommended: 'ਸਿਫ਼ਾਰਸ਼ ਕੀਤੇ ਮਿਆਰ', recommendedDesc: 'ਕੱਢੀ PDF ਸਮੱਗਰੀ ਅਤੇ ਪਛਾਣੇ ਹਵਾਲਿਆਂ ਤੋਂ ਮੇਲ ਬਣਾਏ ਗਏ ਹਨ।', matches: 'ਮੇਲ', failed: 'PDF ਵਿਸ਼ਲੇਸ਼ਣ ਅਸਫਲ ਰਿਹਾ', matched: 'BIS ਮਿਆਰ ਮਿਲੇ', page: 'ਪੰਨਾ' },
  or: { label: 'BIS ଇଣ୍ଟେଲିଜେନ୍ସ', title: 'PDF ବିଶ୍ଳେଷଣ', description: 'ଗଠନ ବାହାର କରିବା, BIS ସନ୍ଦର୍ଭ ଚିହ୍ନଟ କରିବା ଏବଂ ସମ୍ପର୍କିତ ମାନକ ଖୋଜିବା ପାଇଁ PDF ଅପଲୋଡ କରନ୍ତୁ।', source: 'ମୂଳ ଦଲିଲ', hint: 'ସେମାଣ୍ଟିକ ମେଳ ପୂର୍ବରୁ ପ୍ରତ୍ୟେକ ପୃଷ୍ଠାରୁ ପାଠ୍ୟ ବାହାର କରାଯାଏ।', analysis: 'ଦଲିଲ ବିଶ୍ଳେଷଣ', pages: 'ପୃଷ୍ଠା', readable: 'ପଢ଼ିହେବା ପୃଷ୍ଠା', words: 'ବାହାର କରାଯାଇଥିବା ଶବ୍ଦ', refs: 'BIS ସନ୍ଦର୍ଭ', notes: 'ନିଷ୍କାଷଣ ଟିପ୍ପଣୀ', detected: 'ଚିହ୍ନଟ BIS ମାନକ', none: 'କିଛି ମିଳିଲା ନାହିଁ', sections: 'ଦଲିଲ ବିଭାଗ', noSections: 'ମାନକ ବିଭାଗ ଶୀର୍ଷକ ଚିହ୍ନଟ ହୋଇନାହିଁ', referenced: 'ସନ୍ଦର୍ଭିତ ମାନକ', noRefs: 'କୌଣସି IS ସନ୍ଦର୍ଭ ଚିହ୍ନଟ ହୋଇନାହିଁ', details: 'ପୃଷ୍ଠା ନିଷ୍କାଷଣ ବିବରଣୀ', ready: 'ଦଲିଲ ବିଶ୍ଳେଷଣ ପାଇଁ ପ୍ରସ୍ତୁତ', readyDesc: 'PDF ଟେକ୍ସਟ୍ ଲੇୟਰ, ਪ੍ਰଷ્ઠਾ ਕਵਰੇਜ, BIS ਨੰਬਰ, ਵਿਭਾਗ, ਸੰਦਰਭ ਅਤੇ ਸੇਮੈਂਟਿਕ ਸਮਾਨਤਾ ਦੀ ਜਾਂਚ ਕਰੇਗਾ।', recommended: 'ସୁପାରିଶ କରାଯାଇଥିବା ମାନକ', recommendedDesc: 'ବାହାର କରାଯାଇଥିବା PDF ବିଷୟବସ୍ତୁ ଏବଂ ଚିହ୍ନଟ ସନ୍ଦର୍ଭରୁ ମେଳ ସୃଷ୍ଟି ହୋଇଛି।', matches: 'ମେଳ', failed: 'PDF ବିଶ୍ଳେଷଣ ବିଫଳ', matched: 'BIS ମାନକ ମେଳିଲା', page: 'ପୃଷ୍ଠା' },
  ur: { label: 'BIS انٹیلی جنس', title: 'PDF تجزیہ', description: 'ساخت نکالنے، BIS حوالہ جات کی شناخت اور معنوی طور پر متعلقہ معیارات تلاش کرنے کے لیے وضاحتی یا تکنیکی PDF اپ لوڈ کریں۔', source: 'ماخذ دستاویز', hint: 'معنوی مطابقت سے پہلے متن صفحہ بہ صفحہ نکالا جاتا ہے۔', analysis: 'دستاویز کا تجزیہ', pages: 'صفحات', readable: 'قابلِ مطالعہ صفحات', words: 'اخذ کردہ الفاظ', refs: 'BIS حوالہ جات', notes: 'اخذ کرنے کے نوٹس', detected: 'شناخت شدہ BIS معیارات', none: 'کچھ نہیں ملا', sections: 'دستاویز کے حصے', noSections: 'معیاری حصوں کے عنوانات نہیں ملے', referenced: 'حوالہ دیے گئے معیارات', noRefs: 'کوئی IS حوالہ نہیں ملا', details: 'صفحہ وار اخراج کی تفصیلات', ready: 'دستاویز کے تجزیے کے لیے تیار', readyDesc: 'تجزیہ PDF ٹیکسٹ لیئر، صفحہ کوریج، BIS نمبرز، معیاری حصوں، حوالہ جات اور معنوی مماثلت کا جائزہ لے گا۔', recommended: 'تجویز کردہ معیارات', recommendedDesc: 'اخذ کردہ PDF مواد، شناخت شدہ حوالہ جات اور دستاویز کی ساخت سے مماثلتیں تیار کی گئی ہیں۔', matches: 'مماثلتیں', failed: 'PDF تجزیہ ناکام ہوگیا', matched: 'BIS معیارات ملے', page: 'صفحہ' },
}
const SIMILARITY_COPY: Record<Lang, Record<string, string>> = {
  en: { similarityMapTitle: 'Semantic Similarity Map', similarityMapDesc: 'Standards closer to the query are semantically more similar.', standards: 'Standards', query: 'Query', matchScore: 'Match score', xAxis: 'X', yAxis: 'Y' },
  hi: { similarityMapTitle: 'सिमेंटिक समानता मानचित्र', similarityMapDesc: 'क्वेरी के अधिक निकट मानकों में अधिक सिमेंटिक समानता होती है।', standards: 'मानक', query: 'क्वेरी', matchScore: 'मिलान स्कोर', xAxis: 'X', yAxis: 'Y' },
  ta: { similarityMapTitle: 'சொற்பொருள் ஒற்றுமை வரைபடம்', similarityMapDesc: 'வினவலுக்கு அருகிலுள்ள தரநிலைகள் அதிக சொற்பொருள் ஒற்றுமை கொண்டவை.', standards: 'தரநிலைகள்', query: 'வினவல்', matchScore: 'பொருத்த மதிப்பெண்', xAxis: 'X', yAxis: 'Y' },
  bn: { similarityMapTitle: 'সেমান্টিক সাদৃশ্য মানচিত্র', similarityMapDesc: 'কোয়েরির কাছাকাছি মানগুলির সেমান্টিক সাদৃশ্য বেশি।', standards: 'মান', query: 'কোয়েরি', matchScore: 'মিলের স্কোর', xAxis: 'X', yAxis: 'Y' },
  te: { similarityMapTitle: 'సెమాంటిక్ సారూప్యత మ్యాప్', similarityMapDesc: 'క్వెరీకి దగ్గరగా ఉన్న ప్రమాణాలు ఎక్కువ సెమాంటిక్ సారూప్యతను కలిగి ఉంటాయి.', standards: 'ప్రమాణాలు', query: 'క్వెరీ', matchScore: 'మ్యాచ్ స్కోర్', xAxis: 'X', yAxis: 'Y' },
  mr: { similarityMapTitle: 'सिमेंटिक साम्य नकाशा', similarityMapDesc: 'क्वेरीच्या जवळ असलेल्या मानकांमध्ये अधिक सिमेंटिक साम्य असते.', standards: 'मानके', query: 'क्वेरी', matchScore: 'जुळणी गुण', xAxis: 'X', yAxis: 'Y' },
  gu: { similarityMapTitle: 'સેમેન્ટિક સમાનતા નકશો', similarityMapDesc: 'ક્વેરીની નજીકના ધોરણોમાં વધુ સેમેન્ટિક સમાનતા હોય છે.', standards: 'ધોરણો', query: 'ક્વેરી', matchScore: 'મેચ સ્કોર', xAxis: 'X', yAxis: 'Y' },
  kn: { similarityMapTitle: 'ಸೆಮ್ಯಾಂಟಿಕ್ ಸಾಮ್ಯತೆ ನಕ್ಷೆ', similarityMapDesc: 'ಕ್ವೆರಿಗೆ ಹತ್ತಿರವಿರುವ ಮಾನದಂಡಗಳು ಹೆಚ್ಚು ಸೆಮ್ಯಾಂಟಿಕ್ ಸಾಮ್ಯತೆಯನ್ನು ಹೊಂದಿವೆ.', standards: 'ಮಾನದಂಡಗಳು', query: 'ಕ್ವೆರಿ', matchScore: 'ಹೊಂದಾಣಿಕೆ ಅಂಕ', xAxis: 'X', yAxis: 'Y' },
  ml: { similarityMapTitle: 'സെമാന്റിക് സാമ്യ മാപ്പ്', similarityMapDesc: 'ക്വറിയോട് അടുത്തുള്ള മാനദണ്ഡങ്ങൾക്ക് കൂടുതൽ സെമാന്റിക് സാമ്യമുണ്ട്.', standards: 'മാനദണ്ഡങ്ങൾ', query: 'ക്വറി', matchScore: 'പൊരുത്ത സ്കോർ', xAxis: 'X', yAxis: 'Y' },
  pa: { similarityMapTitle: 'ਸੈਮੈਂਟਿਕ ਸਮਾਨਤਾ ਨਕਸ਼ਾ', similarityMapDesc: 'ਕਿਊਰੀ ਦੇ ਨੇੜੇ ਮਿਆਰਾਂ ਵਿੱਚ ਵਧੇਰੇ ਸੈਮੈਂਟਿਕ ਸਮਾਨਤਾ ਹੁੰਦੀ ਹੈ।', standards: 'ਮਿਆਰ', query: 'ਕਿਊਰੀ', matchScore: 'ਮੇਲ ਸਕੋਰ', xAxis: 'X', yAxis: 'Y' },
  or: { similarityMapTitle: 'ସେମାଣ୍ଟିକ ସାମ୍ୟତା ମାନଚିତ୍ର', similarityMapDesc: 'କ୍ୱେରୀର ନିକଟତମ ମାନକଗୁଡ଼ିକର ସେମାଣ୍ଟିକ ସାମ୍ୟତା ଅଧିକ।', standards: 'ମାନକ', query: 'କ୍ୱେରୀ', matchScore: 'ମେଳ ସ୍କୋର', xAxis: 'X', yAxis: 'Y' },
  ur: { similarityMapTitle: 'معنوی مماثلت کا نقشہ', similarityMapDesc: 'استفسار کے قریب معیارات میں معنوی مماثلت زیادہ ہوتی ہے۔', standards: 'معیارات', query: 'استفسار', matchScore: 'مطابقت اسکور', xAxis: 'X', yAxis: 'Y' },
}
Object.entries(SIMILARITY_COPY).forEach(([lang, values]) => Object.assign(PDF_COPY[lang as Lang], values))


const PDF_PAGE_COPY: Record<Lang, Record<string, string>> = {
  en: { pageLabel: 'BIS Intelligence', sourceHint: 'Text is extracted page-by-page before semantic matching.', standardsMatched: 'BIS standards matched', pdfFailed: 'PDF analysis failed' },
  hi: { pageLabel: 'बीआईएस इंटेलिजेंस', sourceHint: 'सिमेंटिक मिलान से पहले पाठ को पृष्ठ-दर-पृष्ठ निकाला जाता है।', standardsMatched: 'BIS मानक मिले', pdfFailed: 'PDF विश्लेषण विफल हुआ' },
  ta: { pageLabel: 'BIS நுண்ணறிவு', sourceHint: 'சொற்பொருள் பொருத்தத்திற்கு முன் உரை ஒவ்வொரு பக்கமாக பிரித்தெடுக்கப்படுகிறது.', standardsMatched: 'BIS தரநிலைகள் பொருந்தின', pdfFailed: 'PDF பகுப்பாய்வு தோல்வியடைந்தது' },
  bn: { pageLabel: 'BIS ইন্টেলিজেন্স', sourceHint: 'সেমান্টিক মিলের আগে প্রতি পৃষ্ঠা থেকে পাঠ্য বের করা হয়।', standardsMatched: 'BIS মান মিলে গেছে', pdfFailed: 'PDF বিশ্লেষণ ব্যর্থ হয়েছে' },
  te: { pageLabel: 'BIS ఇంటెలిజెన్స్', sourceHint: 'సెమాంటిక్ మ్యాచ్‌కు ముందు ప్రతి పేజీ నుంచి వచనం వెలికితీయబడుతుంది.', standardsMatched: 'BIS ప్రమాణాలు సరిపోలాయి', pdfFailed: 'PDF విశ్లేషణ విఫలమైంది' },
  mr: { pageLabel: 'BIS इंटेलिजन्स', sourceHint: 'सिमेंटिक जुळणीपूर्वी मजकूर प्रत्येक पानातून काढला जातो.', standardsMatched: 'BIS मानके जुळली', pdfFailed: 'PDF विश्लेषण अयशस्वी झाले' },
  gu: { pageLabel: 'BIS ઇન્ટેલિજન્સ', sourceHint: 'સેમેન્ટિક મેચિંગ પહેલાં દરેક પાનામાંથી ટેક્સ્ટ કાઢવામાં આવે છે.', standardsMatched: 'BIS ધોરણો મળ્યા', pdfFailed: 'PDF વિશ્લેષણ નિષ્ફળ થયું' },
  kn: { pageLabel: 'BIS ಇಂಟೆಲಿಜೆನ್ಸ್', sourceHint: 'ಸೆಮ್ಯಾಂಟಿಕ್ ಹೊಂದಾಣಿಕೆಯ ಮೊದಲು ಪ್ರತಿ ಪುಟದಿಂದ ಪಠ್ಯವನ್ನು ಹೊರತೆಗೆಯಲಾಗುತ್ತದೆ.', standardsMatched: 'BIS ಮಾನದಂಡಗಳು ಹೊಂದಿಕೆಯಾಗಿವೆ', pdfFailed: 'PDF ವಿಶ್ಲೇಷಣೆ ವಿಫಲವಾಗಿದೆ' },
  ml: { pageLabel: 'BIS ഇന്റലിജൻസ്', sourceHint: 'സെമാന്റിക് പൊരുത്തത്തിന് മുമ്പ് ഓരോ പേജിൽ നിന്നും ടെക്സ്റ്റ് പുറത്തെടുക്കുന്നു.', standardsMatched: 'BIS മാനദണ്ഡങ്ങൾ പൊരുത്തപ്പെട്ടു', pdfFailed: 'PDF വിശകലനം പരാജയപ്പെട്ടു' },
  pa: { pageLabel: 'BIS ਇੰਟੈਲੀਜੈਂਸ', sourceHint: 'ਸੈਮੈਂਟਿਕ ਮਿਲਾਣ ਤੋਂ ਪਹਿਲਾਂ ਹਰ ਪੰਨੇ ਤੋਂ ਪਾਠ ਕੱਢਿਆ ਜਾਂਦਾ ਹੈ।', standardsMatched: 'BIS ਮਿਆਰ ਮਿਲੇ', pdfFailed: 'PDF ਵਿਸ਼ਲੇਸ਼ਣ ਅਸਫਲ ਰਿਹਾ' },
  or: { pageLabel: 'BIS ଇଣ୍ଟେଲିଜେନ୍ସ', sourceHint: 'ସେମାଣ୍ଟିକ ମେଳ ପୂର୍ବରୁ ପ୍ରତ୍ୟେକ ପୃଷ୍ଠାରୁ ପାଠ୍ୟ ବାହାର କରାଯାଏ।', standardsMatched: 'BIS ମାନକ ମେଳିଲା', pdfFailed: 'PDF ବିଶ୍ଳେଷଣ ବିଫଳ' },
  ur: { pageLabel: 'BIS انٹیلی جنس', sourceHint: 'معنوی مطابقت سے پہلے متن صفحہ بہ صفحہ نکالا جاتا ہے۔', standardsMatched: 'BIS معیارات ملے', pdfFailed: 'PDF تجزیہ ناکام ہوگیا' },
}
Object.entries(PDF_PAGE_COPY).forEach(([lang, values]) => Object.assign(PDF_COPY[lang as Lang], values))

function pdfCopy(lang: Lang, key: string): string {
  return PDF_COPY[lang][key] ?? PDF_COPY.en[key] ?? key
}


const EXTRA_COPY: Record<Lang, Record<string, string>> = {
  en: { characters: 'chars', semanticTitle: 'Semantic Match Overview', semanticDesc: 'Standards ranked by semantic similarity to your search.', matches: 'matches', matchScore: 'Match score', generatingReport: 'Generating PDF...', generateReport: 'Generate PDF Report', latest: 'Latest', 'category.normative_reference': 'normative references', 'category.test_method': 'test methods', 'category.terminology': 'terminology', 'category.safety': 'safety standards', 'category.installation': 'installation standards', 'category.product_spec': 'product specifications', 'category.supersedes': 'supersedes', 'category.superseded_by': 'superseded by' },
  hi: { characters: 'अक्षर', semanticTitle: 'सिमेंटिक मिलान अवलोकन', semanticDesc: 'आपकी खोज से सिमेंटिक समानता के आधार पर मानक क्रमबद्ध हैं।', matches: 'मिलान', matchScore: 'मिलान स्कोर', generatingReport: 'PDF तैयार हो रही है…', generateReport: 'PDF रिपोर्ट तैयार करें', latest: 'नवीनतम', 'category.normative_reference': 'मानक संदर्भ', 'category.test_method': 'परीक्षण विधियाँ', 'category.terminology': 'पारिभाषिक शब्दावली', 'category.safety': 'सुरक्षा मानक', 'category.installation': 'स्थापना मानक', 'category.product_spec': 'उत्पाद विनिर्देश', 'category.supersedes': 'इससे प्रतिस्थापित', 'category.superseded_by': 'इसके द्वारा प्रतिस्थापित' },
  ta: { characters: 'எழுத்துகள்', semanticTitle: 'சொற்பொருள் பொருத்தக் கண்ணோட்டம்', semanticDesc: 'உங்கள் தேடலுக்கான சொற்பொருள் ஒற்றுமையின் அடிப்படையில் தரநிலைகள் வரிசைப்படுத்தப்பட்டுள்ளன.', matches: 'பொருத்தங்கள்', matchScore: 'பொருத்த மதிப்பெண்', generatingReport: 'PDF உருவாக்கப்படுகிறது…', generateReport: 'PDF அறிக்கையை உருவாக்கு', latest: 'சமீபத்திய', 'category.normative_reference': 'நெறிமுறை குறிப்புகள்', 'category.test_method': 'சோதனை முறைகள்', 'category.terminology': 'சொற்களஞ்சியம்', 'category.safety': 'பாதுகாப்பு தரநிலைகள்', 'category.installation': 'நிறுவல் தரநிலைகள்', 'category.product_spec': 'தயாரிப்பு விவரக்குறிப்புகள்', 'category.supersedes': 'இதனால் மாற்றப்படுகிறது', 'category.superseded_by': 'இதனால் மாற்றப்பட்டது' },
  bn: { characters: 'অক্ষর', semanticTitle: 'সেমান্টিক মিলের সংক্ষিপ্তসার', semanticDesc: 'আপনার অনুসন্ধানের সঙ্গে সেমান্টিক সাদৃশ্য অনুযায়ী মানগুলি সাজানো হয়েছে।', matches: 'মিল', matchScore: 'মিলের স্কোর', generatingReport: 'PDF তৈরি হচ্ছে…', generateReport: 'PDF রিপোর্ট তৈরি করুন', latest: 'সর্বশেষ', 'category.normative_reference': 'মানক রেফারেন্স', 'category.test_method': 'পরীক্ষার পদ্ধতি', 'category.terminology': 'পরিভাষা', 'category.safety': 'নিরাপত্তা মান', 'category.installation': 'স্থাপন মান', 'category.product_spec': 'পণ্যের স্পেসিফিকেশন', 'category.supersedes': 'প্রতিস্থাপন করে', 'category.superseded_by': 'দ্বারা প্রতিস্থাপিত' },
  te: { characters: 'అక్షరాలు', semanticTitle: 'సెమాంటిక్ మ్యాచ్ అవలోకనం', semanticDesc: 'మీ శోధనకు సెమాంటిక్ సారూప్యత ఆధారంగా ప్రమాణాలు క్రమబద్ధీకరించబడ్డాయి.', matches: 'మ్యాచ్‌లు', matchScore: 'మ్యాచ్ స్కోర్', generatingReport: 'PDF రూపొందుతోంది…', generateReport: 'PDF నివేదికను రూపొందించండి', latest: 'తాజా', 'category.normative_reference': 'నియమబద్ధ సూచనలు', 'category.test_method': 'పరీక్షా పద్ధతులు', 'category.terminology': 'పరిభాష', 'category.safety': 'భద్రతా ప్రమాణాలు', 'category.installation': 'స్థాపన ప్రమాణాలు', 'category.product_spec': 'ఉత్పత్తి వివరణలు', 'category.supersedes': 'దీన్ని భర్తీ చేస్తుంది', 'category.superseded_by': 'దీనిచే భర్తీ చేయబడింది' },
  mr: { characters: 'अक्षरे', semanticTitle: 'सिमेंटिक जुळणी आढावा', semanticDesc: 'तुमच्या शोधाशी सिमेंटिक साम्याच्या आधारे मानके क्रमवारीत आहेत.', matches: 'जुळण्या', matchScore: 'जुळणी गुण', generatingReport: 'PDF तयार होत आहे…', generateReport: 'PDF अहवाल तयार करा', latest: 'नवीनतम', 'category.normative_reference': 'मानक संदर्भ', 'category.test_method': 'चाचणी पद्धती', 'category.terminology': 'परिभाषा', 'category.safety': 'सुरक्षा मानके', 'category.installation': 'स्थापना मानके', 'category.product_spec': 'उत्पादन तपशील', 'category.supersedes': 'याने बदलले', 'category.superseded_by': 'याने बदलले गेले' },
  gu: { characters: 'અક્ષરો', semanticTitle: 'સેમેન્ટિક મેચ ઝાંખી', semanticDesc: 'તમારી શોધ સાથેની સેમેન્ટિક સમાનતા અનુસાર ધોરણો ક્રમબદ્ધ છે.', matches: 'મેચ', matchScore: 'મેચ સ્કોર', generatingReport: 'PDF તૈયાર થઈ રહ્યું છે…', generateReport: 'PDF રિપોર્ટ બનાવો', latest: 'નવીનતમ', 'category.normative_reference': 'ધોરણ સંદર્ભો', 'category.test_method': 'પરીક્ષણ પદ્ધતિઓ', 'category.terminology': 'પરિભાષા', 'category.safety': 'સુરક્ષા ધોરણો', 'category.installation': 'સ્થાપન ધોરણો', 'category.product_spec': 'ઉત્પાદન વિશિષ્ટતાઓ', 'category.supersedes': 'આને બદલે', 'category.superseded_by': 'આના દ્વારા બદલાયેલ' },
  kn: { characters: 'ಅಕ್ಷರಗಳು', semanticTitle: 'ಸೆಮ್ಯಾಂಟಿಕ್ ಹೊಂದಾಣಿಕೆ ಅವಲೋಕನ', semanticDesc: 'ನಿಮ್ಮ ಹುಡುಕಾಟದೊಂದಿಗೆ ಸೆಮ್ಯಾಂಟಿಕ್ ಸಾಮ್ಯತೆಯ ಆಧಾರದ ಮೇಲೆ ಮಾನದಂಡಗಳನ್ನು ಕ್ರಮಗೊಳಿಸಲಾಗಿದೆ.', matches: 'ಹೊಂದಾಣಿಕೆಗಳು', matchScore: 'ಹೊಂದಾಣಿಕೆ ಅಂಕ', generatingReport: 'PDF ಸಿದ್ಧವಾಗುತ್ತಿದೆ…', generateReport: 'PDF ವರದಿ ರಚಿಸಿ', latest: 'ಇತ್ತೀಚಿನ', 'category.normative_reference': 'ಮಾನಕ ಉಲ್ಲೇಖಗಳು', 'category.test_method': 'ಪರೀಕ್ಷಾ ವಿಧಾನಗಳು', 'category.terminology': 'ಪರಿಭಾಷೆ', 'category.safety': 'ಸುರಕ್ಷತಾ ಮಾನದಂಡಗಳು', 'category.installation': 'ಸ್ಥಾಪನಾ ಮಾನದಂಡಗಳು', 'category.product_spec': 'ಉತ್ಪನ್ನ ವಿಶೇಷಣಗಳು', 'category.supersedes': 'ಇದನ್ನು ಬದಲಿಸುತ್ತದೆ', 'category.superseded_by': 'ಇದರಿಂದ ಬದಲಾಯಿಸಲಾಗಿದೆ' },
  ml: { characters: 'അക്ഷരങ്ങൾ', semanticTitle: 'സെമാന്റിക് പൊരുത്ത അവലോകനം', semanticDesc: 'നിങ്ങളുടെ തിരച്ചിലുമായുള്ള സെമാന്റിക് സാമ്യം അനുസരിച്ച് മാനദണ്ഡങ്ങൾ ക്രമീകരിച്ചിരിക്കുന്നു.', matches: 'പൊരുത്തങ്ങൾ', matchScore: 'പൊരുത്ത സ്കോർ', generatingReport: 'PDF തയ്യാറാക്കുന്നു…', generateReport: 'PDF റിപ്പോർട്ട് സൃഷ്ടിക്കുക', latest: 'ഏറ്റവും പുതിയത്', 'category.normative_reference': 'മാനദണ്ഡ റഫറൻസുകൾ', 'category.test_method': 'പരിശോധനാ രീതികൾ', 'category.terminology': 'പദാവലി', 'category.safety': 'സുരക്ഷാ മാനദണ്ഡങ്ങൾ', 'category.installation': 'ഇൻസ്റ്റലേഷൻ മാനദണ്ഡങ്ങൾ', 'category.product_spec': 'ഉൽപ്പന്ന സവിശേഷതകൾ', 'category.supersedes': 'ഇത് മാറ്റിസ്ഥാപിക്കുന്നു', 'category.superseded_by': 'ഇതിനാൽ മാറ്റിസ്ഥാപിച്ചു' },
  pa: { characters: 'ਅੱਖਰ', semanticTitle: 'ਸੈਮੈਂਟਿਕ ਮਿਲਾਣ ਝਲਕ', semanticDesc: 'ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਸੈਮੈਂਟਿਕ ਸਮਾਨਤਾ ਅਨੁਸਾਰ ਮਿਆਰ ਕ੍ਰਮਬੱਧ ਹਨ।', matches: 'ਮੇਲ', matchScore: 'ਮੇਲ ਸਕੋਰ', generatingReport: 'PDF ਤਿਆਰ ਹੋ ਰਹੀ ਹੈ…', generateReport: 'PDF ਰਿਪੋਰਟ ਬਣਾਓ', latest: 'ਨਵੀਨਤਮ', 'category.normative_reference': 'ਮਿਆਰੀ ਹਵਾਲੇ', 'category.test_method': 'ਟੈਸਟ ਵਿਧੀਆਂ', 'category.terminology': 'ਸ਼ਬਦਾਵਲੀ', 'category.safety': 'ਸੁਰੱਖਿਆ ਮਿਆਰ', 'category.installation': 'ਸਥਾਪਨਾ ਮਿਆਰ', 'category.product_spec': 'ਉਤਪਾਦ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ', 'category.supersedes': 'ਇਸਦੀ ਥਾਂ ਲੈਂਦਾ ਹੈ', 'category.superseded_by': 'ਇਸ ਨਾਲ ਬਦਲਿਆ ਗਿਆ' },
  or: { characters: 'ଅକ୍ଷର', semanticTitle: 'ସେମାଣ୍ଟିକ ମେଳ ସମୀକ୍ଷା', semanticDesc: 'ଆପଣଙ୍କ ସନ୍ଧାନ ସହିତ ସେମାଣ୍ଟିକ ସାମ୍ୟ ଅନୁସାରେ ମାନକଗୁଡ଼ିକୁ କ୍ରମିତ କରାଯାଇଛି।', matches: 'ମେଳ', matchScore: 'ମେଳ ସ୍କୋର', generatingReport: 'PDF ପ୍ରସ୍ତୁତ ହେଉଛି…', generateReport: 'PDF ରିପୋର୍ଟ ପ୍ରସ୍ତୁତ କରନ୍ତୁ', latest: 'ସର୍ବଶେଷ', 'category.normative_reference': 'ମାନକ ସନ୍ଦର୍ଭ', 'category.test_method': 'ପରୀକ୍ଷା ପଦ୍ଧତି', 'category.terminology': 'ପରିଭାଷା', 'category.safety': 'ସୁରକ୍ଷା ମାନକ', 'category.installation': 'ସ୍ଥାପନ ମାନକ', 'category.product_spec': 'ଉତ୍ପାଦ ବିବରଣୀ', 'category.supersedes': 'ଏହାକୁ ବଦଳାଏ', 'category.superseded_by': 'ଏହାଦ୍ୱାରା ବଦଳାଯାଇଛି' },
  ur: { characters: 'حروف', semanticTitle: 'معنوی مطابقت کا جائزہ', semanticDesc: 'آپ کی تلاش سے معنوی مماثلت کے مطابق معیارات کی درجہ بندی کی گئی ہے۔', matches: 'مماثلتیں', matchScore: 'مطابقت اسکور', generatingReport: 'PDF تیار ہو رہی ہے…', generateReport: 'PDF رپورٹ تیار کریں', latest: 'تازہ ترین', 'category.normative_reference': 'معیاری حوالہ جات', 'category.test_method': 'طریقہ ہائے جانچ', 'category.terminology': 'اصطلاحات', 'category.safety': 'حفاظتی معیارات', 'category.installation': 'تنصیب کے معیارات', 'category.product_spec': 'مصنوعات کی خصوصیات', 'category.supersedes': 'اسے منسوخ کرتا ہے', 'category.superseded_by': 'اس کے ذریعے منسوخ کیا گیا' },
}

Object.entries(EXTRA_COPY).forEach(([lang, values]) => Object.assign(PDF_COPY[lang as Lang], values))

function pdfCopy(lang: Lang, key: string): string {
  return PDF_COPY[lang][key] ?? PDF_COPY.en[key] ?? key
}

export { PDF_COPY, pdfCopy }
